#!/usr/bin/env python3
"""VOS Fabric G4/G5 real-runtime certification harness.

The harness is deliberately split into stage1/stage2 so G5 crosses a real process
boundary and reloads its durable checkpoint from disk. It never receives a founder
prompt. All model prompts are fixed, versioned strings generated by this file.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, Mapping, Tuple


MANDATE_ID = "T-VOS-FABRIC-G4-G5"
G3_CERTIFIED_SHA = "1f16ab2505480adab67b20411cf0b5819179a2b2"
WORKER_ID = "codex-g2-live"
EFFECT_ID = "g5-isolated-certification-write-once"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_text(text: str) -> str:
    return sha256_bytes(text.encode("utf-8"))


def read_json(path: Path) -> Dict[str, Any]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise RuntimeError("%s must contain a JSON object" % path)
    return raw


def write_json(path: Path, value: Mapping[str, Any]) -> None:
    path.write_text(
        json.dumps(dict(value), sort_keys=True, indent=2) + "\n",
        encoding="utf-8",
    )


def load_fabric(fabric_dir: Path):
    sys.path.insert(0, str(fabric_dir))
    import bridge  # type: ignore
    import checkpoint  # type: ignore
    import rollover  # type: ignore
    import worker_adapter  # type: ignore
    return bridge, checkpoint, rollover, worker_adapter


def validate_mandate(md_path: Path, json_path: Path) -> Dict[str, Any]:
    manifest = read_json(json_path)
    required = {
        "schema_version", "unit_id", "label", "risk", "lane",
        "base_certified_g3_sha", "mandate_md", "mandate_sha256", "key",
        "founder_go", "authorization_class", "max_cost_usd",
        "paid_api_fallback", "quota_circumvention", "production_mutation",
        "isolated_effect_scope", "gates",
    }
    if set(manifest) != required:
        raise RuntimeError("mandate manifest fields are not exact")
    if manifest["schema_version"] != 1 or manifest["unit_id"] != MANDATE_ID:
        raise RuntimeError("mandate schema/id mismatch")
    if manifest["label"] != "CONFIRM_FIRST" or manifest["risk"] != "B":
        raise RuntimeError("runtime mandate must remain CONFIRM_FIRST risk B")
    if manifest["base_certified_g3_sha"] != G3_CERTIFIED_SHA:
        raise RuntimeError("mandate not bound to certified G3 SHA")
    if manifest["founder_go"] is not True:
        raise RuntimeError("founder GO missing")
    if manifest["authorization_class"] != "FOUNDER_CONFIRMED_RUNTIME_CERTIFICATION":
        raise RuntimeError("authorization class mismatch")
    if manifest["max_cost_usd"] != 0:
        raise RuntimeError("nonzero cost forbidden")
    if manifest["paid_api_fallback"] is not False:
        raise RuntimeError("paid API fallback must be false")
    if manifest["quota_circumvention"] is not False:
        raise RuntimeError("quota circumvention must be false")
    if manifest["production_mutation"] is not False:
        raise RuntimeError("production mutation must be false")
    if manifest["isolated_effect_scope"] != "vos-worker-temporary":
        raise RuntimeError("effect scope mismatch")
    if manifest["gates"] != ["G4", "G5"]:
        raise RuntimeError("gate scope mismatch")
    actual = sha256_bytes(md_path.read_bytes())
    if actual != manifest["mandate_sha256"]:
        raise RuntimeError("mandate Markdown SHA-256 mismatch")
    return manifest


def explicit_worker_env(proxy_url: str) -> Dict[str, str]:
    return {
        "HOME": "/home/ubuntu",
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "CODEX_HOME": "/home/ubuntu/.codex-vos-fabric",
        "HTTPS_PROXY": proxy_url,
        "HTTP_PROXY": proxy_url,
        "https_proxy": proxy_url,
        "http_proxy": proxy_url,
        "LC_ALL": "C",
        "LANG": "C",
    }


def make_worker_spec(
    runtime_dir: Path,
    live_worker: Path,
    *,
    mode: str,
    thread_id: str,
    model: str,
    prefix: str,
    expected_message: str,
    proxy_url: str,
    authorization_ref: str,
) -> Tuple[Dict[str, Any], Path]:
    prompt_path = runtime_dir / ("%s.prompt" % prefix)
    events_path = runtime_dir / ("%s.events.jsonl" % prefix)
    message_path = runtime_dir / ("%s.message.txt" % prefix)
    evidence_path = runtime_dir / ("%s.evidence.json" % prefix)
    if mode == "resume" and prefix == "g4":
        prompt = "Reply exactly: VOS_G4_RUNTIME=OK\n"
    elif mode == "fork":
        prompt = "Reply exactly: VOS_G5_FORK=OK\n"
    elif mode == "resume":
        prompt = "Reply exactly: VOS_G5_CONTINUE=OK\n"
    else:
        raise RuntimeError("unsupported live worker mode")
    prompt_path.write_text(prompt, encoding="utf-8")

    command = [
        "/usr/bin/python3", str(live_worker),
        "--mode", mode,
        "--thread-id", thread_id,
        "--model", model,
        "--work-dir", str(runtime_dir),
        "--prompt-file", str(prompt_path),
        "--events-file", str(events_path),
        "--message-file", str(message_path),
        "--evidence-file", str(evidence_path),
        "--expected-message", expected_message,
        "--timeout-seconds", "120",
    ]
    spec = {
        "worker_id": WORKER_ID,
        "eligible_workers": [WORKER_ID],
        "data_class": "INTERNAL",
        "max_cost_usd": 0,
        "network": "VOS_AUTHORIZED",
        "network_authorization_ref": authorization_ref,
        "external_effects": False,
        "command": command,
        "allowed_executables": ["/usr/bin/python3"],
        "allowed_paths": [str(runtime_dir)],
        "cwd": str(runtime_dir),
        "timeout_seconds": 180,
        "env": explicit_worker_env(proxy_url),
    }
    return spec, evidence_path


def used_units(usage: Mapping[str, Any]) -> int:
    def find(mapping: Mapping[str, Any]) -> int:
        for key in ("total_tokens", "total_token_count", "total_tokens_used"):
            value = mapping.get(key)
            if isinstance(value, int) and not isinstance(value, bool) and value > 0:
                return value
        input_value = None
        output_value = None
        for key in ("input_tokens", "input_token_count"):
            value = mapping.get(key)
            if isinstance(value, int) and not isinstance(value, bool) and value >= 0:
                input_value = value
                break
        for key in ("output_tokens", "output_token_count"):
            value = mapping.get(key)
            if isinstance(value, int) and not isinstance(value, bool) and value >= 0:
                output_value = value
                break
        if input_value is not None and output_value is not None and input_value + output_value > 0:
            return input_value + output_value
        for value in mapping.values():
            if isinstance(value, Mapping):
                nested = find(value)
                if nested > 0:
                    return nested
        return 0

    value = find(usage)
    if value <= 0:
        raise RuntimeError("live Codex usage telemetry did not expose token units")
    return value


def assert_worker_done(result: Mapping[str, Any]) -> None:
    if result.get("status") != "DONE" or result.get("exit_code") != 0:
        raise RuntimeError("live worker did not complete successfully: %s" % result.get("status"))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("stage", choices=("stage1", "stage2"))
    parser.add_argument("--fabric-dir", required=True)
    parser.add_argument("--runtime-dir", required=True)
    parser.add_argument("--live-worker", required=True)
    parser.add_argument("--mandate-md", required=True)
    parser.add_argument("--mandate-json", required=True)
    parser.add_argument("--authorization-ref", required=True)
    parser.add_argument("--fabric-sha", required=True)
    parser.add_argument("--model", required=True)
    parser.add_argument("--proxy-url", required=True)
    parser.add_argument("--g2-source-thread-id")
    args = parser.parse_args()

    runtime_dir = Path(args.runtime_dir).resolve()
    runtime_dir.mkdir(parents=True, exist_ok=True)
    live_worker = Path(args.live_worker).resolve()
    fabric_dir = Path(args.fabric_dir).resolve()
    manifest = validate_mandate(Path(args.mandate_md), Path(args.mandate_json))
    if manifest["base_certified_g3_sha"] != G3_CERTIFIED_SHA:
        raise RuntimeError("G3 binding mismatch")
    expected_ref_fragment = "mandate_sha256=%s" % manifest["mandate_sha256"]
    if expected_ref_fragment not in args.authorization_ref:
        raise RuntimeError("authorization ref is not bound to mandate SHA-256")
    if "g3=%s" % G3_CERTIFIED_SHA not in args.authorization_ref:
        raise RuntimeError("authorization ref is not bound to certified G3 SHA")

    bridge, checkpoint, rollover, worker_adapter = load_fabric(fabric_dir)
    checkpoint_path = runtime_dir / "g5.checkpoint.json"
    stage1_path = runtime_dir / "g5.stage1.json"
    marker_path = runtime_dir / "g5.effect.marker"

    if args.stage == "stage1":
        if not args.g2_source_thread_id:
            raise RuntimeError("stage1 requires G2 source thread id")

        base_sha256 = sha256_text(G3_CERTIFIED_SHA)
        cp0 = checkpoint.new_checkpoint(
            "VOS-FABRIC-G4-G5-RUNTIME",
            manifest["mandate_sha256"],
            base_sha256,
        )
        spec, evidence_path = make_worker_spec(
            runtime_dir, live_worker,
            mode="resume",
            thread_id=args.g2_source_thread_id,
            model=args.model,
            prefix="g4",
            expected_message="VOS_G4_RUNTIME=OK",
            proxy_url=args.proxy_url,
            authorization_ref=args.authorization_ref,
        )
        prepared = bridge.prepare_dispatch(
            cp0,
            spec,
            vos_authorization_ref=args.authorization_ref,
            continuation_ref=args.g2_source_thread_id,
        )
        if prepared["founder_prompt_shuttling"] != 0:
            raise RuntimeError("bridge reported founder prompt shuttling")
        result = worker_adapter.run_request(prepared["worker_request"])
        assert_worker_done(result)
        consumed = bridge.consume_result(prepared["checkpoint"], result)
        if consumed["founder_prompt_shuttling"] != 0:
            raise RuntimeError("bridge result reported founder prompt shuttling")
        cp1 = consumed["checkpoint"]

        g4_evidence = read_json(evidence_path)
        if g4_evidence["mode"] != "resume":
            raise RuntimeError("G4 mode mismatch")
        if g4_evidence["observed_thread_id"] != args.g2_source_thread_id:
            raise RuntimeError("G4 did not resume exact G2 thread")
        if g4_evidence["paid_api_fallback"] != 0:
            raise RuntimeError("G4 paid API fallback detected")

        units = used_units(g4_evidence.get("usage", {}))
        # Certification uses a bounded VOS context budget derived from real live
        # telemetry. It does NOT claim the provider model's hard context window.
        context_limit = max(units, (units * 100) // 80)
        if units * 100 < context_limit * 80:
            raise RuntimeError("could not construct bounded certification threshold")

        effect_payload = (
            "VOS_G5_ISOLATED_EFFECT:%s:%s\n"
            % (manifest["mandate_sha256"], args.g2_source_thread_id)
        ).encode("utf-8")
        effect_sha = sha256_bytes(effect_payload)
        cp2, claimed_now = checkpoint.claim_effect(cp1, EFFECT_ID, effect_sha)
        if not claimed_now:
            raise RuntimeError("first isolated certification effect was not newly claimed")
        if marker_path.exists():
            raise RuntimeError("isolated effect marker pre-existed")
        marker_path.write_bytes(effect_payload)

        planned = rollover.watch(
            cp2,
            {
                "context_used_units": units,
                "context_limit_units": context_limit,
            },
            threshold_percent=80,
        )
        if planned["action"] != "ROLLOVER" or not planned["planned_now"]:
            raise RuntimeError("G5 rollover was not planned from live telemetry")
        if planned["founder_prompt_shuttling"] != 0:
            raise RuntimeError("rollover watcher reported founder prompt shuttling")
        checkpoint_sha = checkpoint.write_atomic(checkpoint_path, planned["checkpoint"])
        write_json(stage1_path, {
            "schema_version": 1,
            "old_continuation_ref": args.g2_source_thread_id,
            "effect_id": EFFECT_ID,
            "effect_sha256": effect_sha,
            "authorization_ref_sha256": sha256_text(args.authorization_ref),
            "mandate_sha256": manifest["mandate_sha256"],
            "fabric_sha": args.fabric_sha,
            "model": args.model,
            "context_used_units": units,
            "context_limit_units": context_limit,
            "checkpoint_file_sha256": checkpoint_sha,
            "g4_worker_result_sha256": consumed["result_sha256"],
            "g4_events_sha256": g4_evidence["events_sha256"],
            "founder_prompt_shuttling": 0,
        })
        print("G4_REAL_WORKER_CHAIN=GREEN")
        print("FOUNDER_PROMPT_SHUTTLING=0")
        print("G5_DURABLE_CHECKPOINT=WRITTEN")
        print("G5_ROLLOVER_REQUIRED=GREEN")
        print("G5_CONTEXT_TELEMETRY_SOURCE=REAL_CODEX_USAGE")
        print("G5_CONTEXT_LIMIT_CLASS=VOS_CERTIFICATION_BUDGET")
        return 0

    cp = checkpoint.read_checkpoint(checkpoint_path)
    stage1 = read_json(stage1_path)
    if cp["state"] != "ROLLOVER_REQUIRED":
        raise RuntimeError("durable checkpoint is not ROLLOVER_REQUIRED")
    if stage1["authorization_ref_sha256"] != sha256_text(args.authorization_ref):
        raise RuntimeError("authorization ref changed across process boundary")
    if stage1["fabric_sha"] != args.fabric_sha:
        raise RuntimeError("Fabric SHA changed across process boundary")
    if stage1["model"] != args.model:
        raise RuntimeError("model changed across process boundary")
    old_ref = stage1["old_continuation_ref"]
    if cp["continuation_ref"] != old_ref:
        raise RuntimeError("durable old continuation ref mismatch")
    expected_marker = (
        "VOS_G5_ISOLATED_EFFECT:%s:%s\n"
        % (manifest["mandate_sha256"], old_ref)
    ).encode("utf-8")
    if marker_path.read_bytes() != expected_marker:
        raise RuntimeError("isolated effect marker mismatch before rollover")

    fork_spec, fork_evidence_path = make_worker_spec(
        runtime_dir, live_worker,
        mode="fork",
        thread_id=old_ref,
        model=args.model,
        prefix="g5-fork",
        expected_message="VOS_G5_FORK=OK",
        proxy_url=args.proxy_url,
        authorization_ref=args.authorization_ref,
    )
    fork_request = dict(fork_spec)
    fork_request["request_id"] = "vos-rollover-" + sha256_text(
        manifest["mandate_sha256"] + "\0" + old_ref
    )[:24]
    fork_request["mandate_sha256"] = manifest["mandate_sha256"]
    fork_result = worker_adapter.run_request(fork_request)
    assert_worker_done(fork_result)
    fork_evidence = read_json(fork_evidence_path)
    new_ref = fork_evidence["observed_thread_id"]
    if new_ref == old_ref:
        raise RuntimeError("real Codex fork did not change continuation ref")
    if fork_evidence["paid_api_fallback"] != 0:
        raise RuntimeError("G5 fork paid API fallback detected")

    completed = rollover.complete_rollover(
        cp,
        expected_old_continuation_ref=old_ref,
        new_continuation_ref=new_ref,
    )
    if not completed["completed_now"]:
        raise RuntimeError("G5 rollover completion was unexpectedly a replay")
    if completed["founder_prompt_shuttling"] != 0:
        raise RuntimeError("rollover completion reported founder prompt shuttling")
    cp_ready = completed["checkpoint"]

    replay_cp, claimed_now = checkpoint.claim_effect(
        cp_ready,
        stage1["effect_id"],
        stage1["effect_sha256"],
    )
    if claimed_now:
        raise RuntimeError("duplicate isolated effect was re-claimed after rollover")
    if marker_path.read_bytes() != expected_marker:
        raise RuntimeError("isolated effect marker changed on replay")

    resume_spec, resume_evidence_path = make_worker_spec(
        runtime_dir, live_worker,
        mode="resume",
        thread_id=new_ref,
        model=args.model,
        prefix="g5-continue",
        expected_message="VOS_G5_CONTINUE=OK",
        proxy_url=args.proxy_url,
        authorization_ref=args.authorization_ref,
    )
    prepared = bridge.prepare_dispatch(
        replay_cp,
        resume_spec,
        vos_authorization_ref=args.authorization_ref,
        continuation_ref=new_ref,
    )
    if prepared["founder_prompt_shuttling"] != 0:
        raise RuntimeError("post-rollover bridge reported founder prompt shuttling")
    resume_result = worker_adapter.run_request(prepared["worker_request"])
    assert_worker_done(resume_result)
    consumed = bridge.consume_result(prepared["checkpoint"], resume_result)
    if consumed["founder_prompt_shuttling"] != 0:
        raise RuntimeError("post-rollover result reported founder prompt shuttling")
    resume_evidence = read_json(resume_evidence_path)
    if resume_evidence["observed_thread_id"] != new_ref:
        raise RuntimeError("post-rollover exact resume changed continuation ref")
    if resume_evidence["paid_api_fallback"] != 0:
        raise RuntimeError("post-rollover paid API fallback detected")

    final_checkpoint_sha = checkpoint.write_atomic(checkpoint_path, consumed["checkpoint"])
    final_evidence = {
        "schema_version": 1,
        "g4": "GREEN",
        "g5": "GREEN",
        "old_continuation_ref_sha256": sha256_text(old_ref),
        "new_continuation_ref_sha256": sha256_text(new_ref),
        "continuation_changed": True,
        "post_rollover_resume_exact": True,
        "effect_claimed_once": True,
        "effect_replay_claimed_now": False,
        "effect_marker_sha256": sha256_bytes(marker_path.read_bytes()),
        "final_checkpoint_sha256": final_checkpoint_sha,
        "fork_events_sha256": fork_evidence["events_sha256"],
        "continue_events_sha256": resume_evidence["events_sha256"],
        "founder_prompt_shuttling": 0,
        "paid_api_fallback": 0,
        "production_mutations": 0,
        "context_telemetry_source": "REAL_CODEX_USAGE",
        "context_limit_class": "VOS_CERTIFICATION_BUDGET",
    }
    write_json(runtime_dir / "g4-g5-runtime-evidence.json", final_evidence)
    print("G5_REAL_FORK=GREEN")
    print("G5_POST_ROLLOVER_EXACT_RESUME=GREEN")
    print("G5_EFFECT_CLAIMED_ONCE=GREEN")
    print("G5_DUPLICATED_EFFECTS=0")
    print("FOUNDER_PROMPT_SHUTTLING=0")
    print("G4=GREEN")
    print("G5=GREEN")
    print("G4_G5_PAID_API_FALLBACK=0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
