// ─── Ed25519 Sign + Verify (Standard WebCrypto) ──────────────────────
// S291 — Replaces legacy `NODE-ED25519` algorithm (verify-only) in `ed25519.ts`.
// Uses standard `Ed25519` algorithm name (Workers nodejs_compat + Node 22+).
//
// Interop verified S290:
//   Node 22 webcrypto.subtle (PKCS8 import + raw export) ↔ Workers crypto.subtle
//   ↔ ed25519-dalek v2.2.0 Rust (Tauri client verify).
//
// Key formats:
//   PRIVATE: PKCS8 DER base64 (48 bytes inner, generated by SubtleCrypto generateKey)
//   PUBLIC:  raw 32 bytes hex (kid:v1)
//   SIGNATURE: raw 64 bytes base64 (canonical)
//
// MAI usare per le firme legacy ED25519_PUBLIC_KEY (lascia `verifyEd25519` in `ed25519.ts`).

// ─── Helpers ───────────────────────────────────────────────────────

function hexToBytes(hex: string): Uint8Array {
  if (hex.length % 2 !== 0) {
    throw new Error('Invalid hex string length');
  }
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
  }
  return bytes;
}

function base64ToBytes(base64: string): Uint8Array {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

function bytesToBase64(bytes: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

// ─── Key Import ─────────────────────────────────────────────────────

async function importPrivateKeyFromPkcs8Base64(pkcs8Base64: string): Promise<CryptoKey> {
  const pkcs8Bytes = base64ToBytes(pkcs8Base64);
  return crypto.subtle.importKey(
    'pkcs8',
    pkcs8Bytes,
    { name: 'Ed25519' },
    false,
    ['sign'],
  );
}

async function importPublicKeyFromHexRaw(publicKeyHex: string): Promise<CryptoKey> {
  const publicKeyBytes = hexToBytes(publicKeyHex);
  return crypto.subtle.importKey(
    'raw',
    publicKeyBytes,
    { name: 'Ed25519' },
    false,
    ['verify'],
  );
}

// ─── Sign API ──────────────────────────────────────────────────────

/**
 * Sign a UTF-8 string payload with the Worker's Ed25519 private key.
 *
 * @param pkcs8Base64 - Private key in PKCS8 DER base64 (env secret ED25519_PRIVATE_KEY_PKCS8)
 * @param payload - Canonical UTF-8 string to sign (JSON.stringify result)
 * @returns base64-encoded 64-byte Ed25519 signature
 */
export async function signEd25519(
  pkcs8Base64: string,
  payload: string,
): Promise<string> {
  const cryptoKey = await importPrivateKeyFromPkcs8Base64(pkcs8Base64);
  const encoder = new TextEncoder();
  const signatureBuffer = await crypto.subtle.sign(
    'Ed25519',
    cryptoKey,
    encoder.encode(payload),
  );
  return bytesToBase64(new Uint8Array(signatureBuffer));
}

// ─── Verify API ────────────────────────────────────────────────────

/**
 * Verify an Ed25519 signature (standard algo, kid:v1) against payload.
 * Distinct from legacy `verifyEd25519` in `ed25519.ts` (NODE-ED25519 algo).
 *
 * @param publicKeyHex - 32-byte raw public key as hex (env ED25519_PUBLIC_KEY_V1)
 * @param signatureBase64 - Base64-encoded Ed25519 signature (64 bytes)
 * @param payload - UTF-8 string that was signed
 * @returns true if signature is valid
 */
export async function verifyEd25519Standard(
  publicKeyHex: string,
  signatureBase64: string,
  payload: string,
): Promise<boolean> {
  try {
    const cryptoKey = await importPublicKeyFromHexRaw(publicKeyHex);
    const signatureBytes = base64ToBytes(signatureBase64);
    const encoder = new TextEncoder();
    return await crypto.subtle.verify(
      'Ed25519',
      cryptoKey,
      signatureBytes,
      encoder.encode(payload),
    );
  } catch {
    return false;
  }
}

// ─── License Payload Builder (kid:v1, deterministic) ───────────────

export interface LicensePayloadV1 {
  kid: 'v1';
  license_id: string;
  customer_email: string;
  product: 'base' | 'pro';
  session_id: string;
  issued_at: number; // unix epoch seconds
}

/**
 * Build deterministic license_id = sha256(session_id || product || customer_email).
 * Deterministic = replay safety: same Stripe event → same license_id.
 */
export async function computeLicenseId(
  sessionId: string,
  product: 'base' | 'pro',
  customerEmail: string,
): Promise<string> {
  const normalized = `${sessionId}|${product}|${customerEmail.toLowerCase().trim()}`;
  const encoder = new TextEncoder();
  const hashBuffer = await crypto.subtle.digest('SHA-256', encoder.encode(normalized));
  const hashBytes = new Uint8Array(hashBuffer);
  let hex = '';
  for (let i = 0; i < hashBytes.length; i++) {
    hex += hashBytes[i].toString(16).padStart(2, '0');
  }
  return hex;
}

/**
 * Build canonical license payload JSON string (input for signEd25519).
 * Canonical = stable key order (kid, license_id, customer_email, product, session_id, issued_at).
 * Stable ordering is critical: client Tauri verify will re-serialize identically.
 */
export function canonicalizeLicensePayload(payload: LicensePayloadV1): string {
  // Explicit key order — DO NOT use Object.entries (insertion-order != canonical).
  return JSON.stringify({
    kid: payload.kid,
    license_id: payload.license_id,
    customer_email: payload.customer_email,
    product: payload.product,
    session_id: payload.session_id,
    issued_at: payload.issued_at,
  });
}
