# FLUXION — S339 resume — Sara Layer 2 audio. **EHIWEB 403 RISOLTO (numero riattivato). Gate loopback PARCHEGGIATO (S338 verdetto falsificato). PRIMA AZIONE = TEST CHIAMATA REALE SARA via provider.**

> ## >>> SBLOCCO EHIWEB (2026-06-04, founder-input): il `reg_status:403` persistente (S332-S337) era causato dal **numero 0972536918 temporaneamente DISATTIVATO dal provider EHIWEB/vivavox**. Luke conferma: **ora RIPRISTINATO e FUNZIONANTE.** Il BLOCKED-ON esterno è chiuso. Niente whitelist IP / credito / password da toccare — era disattivazione lato provider. <<<
> ## PRIMA AZIONE S339 = OPZIONE 1 (path provider reale, raccomandata S338 e ora sbloccata): (1) Pipeline Sara è DOWN (porta 3002) — riavviarla su iMac PRIMA di tutto. (2) Verificare registrazione SIP verde: `curl http://192.168.1.2:3002/api/voice/voip/status` → atteso `registered:true, reg_status:200` (era 403). (3) Se verde → TEST CHIAMATA REALE Sara CTO-guidato (REGOLA #23: CTO parla via TTS su iMac, NON chiedere a Luke di chiamare). Le chiamate provider S244 NON crashavano (timing rete diluisce la race che il loopback innescava) → questo è il canale Layer 2 funzionante. (4) Validare Sara sui verticali via audio reale (REGOLA #21 "soddisfa pienamente il cliente") — scenari STT-sensitivi via voce, il resto già VERDE Layer 1 testo (S333: 50 OK/3 WARN su 12 verticali).
> ## NB loopback 127.0.0.1: resta non-testabile (bug strutturale pjsua2 confermato S338, vedi sotto) ma NON è più un blocco — il provider reale è la via di validazione. Asterisk ARI archiviato (non serve più).

> ## >>> S338 ESITO BINARIO (2026-06-04, voice-engineer foreground): config del giudice GIÀ implementata nel codice = no-op. Verificato live su iMac: `threadCnt=0` (riga 879) + `mainThreadOnly=True` (riga 880) + libCreate(824)/libHandleEvents(806) STESSO `_pjsua2_thread` + `libInit(ep_cfg)` (902) dopo i flag (ordine corretto) + pjsua2 `2.15.1` live. Restart pipeline + harness loopback `sip:0972536918@127.0.0.1:5080` → **Sara CRASHA IDENTICO**. Log probante fresco (`/tmp/sara-pjsip-s244.log`): `conference.c onCallMediaS Add port 2 (sara_bridge) queued` → `Fatal Python error: Aborted` in `libHandleEvents` (voip_pjsua2.py:806). **`mainThreadOnly=True` è attivo MA NON marshalizza i callback media C-side** (`onCallMediaState`/resample/conferenza) — controlla solo i callback SIP/INV. L'intuizione del giudice (marshaling integrata) era giusta come intent, SBAGLIATA sull'implementazione reale di pjsua2: quel flag non tocca i media callback. <<<
> ## CRITERIO STOP BINARIO DEL GIUDICE SODDISFATTO → diagnosi config FALSIFICATA. Per istruzione esplicita del verdetto (riga 54 di `.claude/cache/agents/s337/claude-ai-response.md`): **NO 4° ciclo autonomo, NO Asterisk senza NUOVO verdetto esterno.** Gate Sara Layer 2 SPOSTATO su "validazione con chiamata reale post-403". Loopback PARCHEGGIATO (resta utile come rete di regressione SOLO se un giorno funzionasse, ma non è prerequisito).
> ## ROOT CAUSE FINALE (3 cicli, firma identica): bug STRUTTURALE pjsua2 — `onCallMediaState` C-side gira su media-thread non disabilitabile né marshalabile; port-add conference da lì setta owner group-lock, `_pjsua2_thread` fa l'unset in `libHandleEvents` → owner mismatch → SIGABRT. Version-independent (2.15.1 e 2.16-dev identici), config-independent (threadCnt/mainThreadOnly/affinity tutti corretti). NON Python-fixabile, NON config-fixabile.
> ## PRIMA AZIONE S339 = DECISIONE FOUNDER (NO azione tecnica autonoma su questo gate, vincolo #1c). Tre opzioni residue, decisione di Luke:
> ##   (1) **Path provider reale EHIWEB** come UNICO canale Layer 2: sbloccare il `reg_status:403` (BLOCKED-ON Luke, pannello EHIWEB — vedi sotto), poi testare Sara su chiamata reale CTO-guidata. Le chiamate provider S244 NON crashavano (timing diluito evita la race loopback). €0, nessun nuovo daemon. RACCOMANDATA.
> ##   (2) **Asterisk ARI** come media layer, Sara solo cervello (rimuove conference bridge pjsua2). Richiede NUOVO verdetto giudice prima di partire (rischio build Big Sur no-AVX2, 2-3gg realistici). Parcheggiata F2/F3.
> ##   (3) Accettare loopback non-testabile, gating Layer 2 esclusivamente su (1).
> ## Se Luke sceglie (2) Asterisk → scrivere prima prompt per giudice esterno (vincolo #1c, evidenza 3 cicli falliti). Memoria agent completa: `.claude/agent-memory/voice-engineer/project_sip_loopback_crash_pjsip216.md` (sezione "S338 binary run").
> ## STATO iMac: pjsua2 2.15.1 in `lib/pjsua2/`, backup 2.16-dev in `lib/pjsua2.backup-PRE-S337-20260604-125255/`. Pipeline Sara DOWN dopo crash harness — riavviare a inizio S339 se serve. Branch iMac `fix/license-interop-r01-s327`.

> --- HANDOFF S338 ORIGINALE (SUPERATO da esito sopra) ---
# FLUXION — S338 resume — Sara Layer 2 audio. **S337 DOWNGRADE 2.15.1 FATTO ma NON RISOLVE. Ipotesi versione FALSIFICATA.**

> ## >>> VERDETTO GIUDICE RICEVUTO (`.claude/cache/agents/s337/claude-ai-response.md`): OPZIONE 1 fix threading — ma NON il deferral già falsificato. Fix = marshaling INTEGRATA pjsua2: `uaConfig.threadCnt=0` + `uaConfig.mainThreadOnly=true` + `libCreate()`/`libHandleEvents()` sullo STESSO thread. NON Asterisk. NON abbandonare il loopback. Root cause = pjsua2 issue #1519 (media/sound thread non disabilitabile chiama callback → owner group-lock mismatch). `mainThreadOnly` marshalizza ANCHE i callback interni pjsip → risolve il crash su `Add port 1` che il deferral Python non poteva toccare. <<<
> ## PRIMA AZIONE S338 (ciclo BOUNDED hard-cap 2h, autorizzato #1c con esito binario): (a) ispeziona config attuale in `voice-agent/src/voip_pjsua2.py`, registra i 3 valori (threadCnt, mainThreadOnly, dove gira libCreate vs libHandleEvents) — la sola lettura dirà quale dei 3 è violato; (b) applica i 3 punti; (c) restart pipeline + ri-run harness loopback. **STOP NETTO**: se ancora aborta su `grp_lock_unset_owner_thread` → diagnosi config FALSIFICATA → sposta gate su "chiamata reale post-403", parcheggia loopback, NO 4° ciclo né Asterisk senza nuovo verdetto esterno. VERIFICARE le fonti del giudice (doc PJSIP threadCnt, issue #1519, UaConfig.mainThreadOnly) PRIMA di applicare (vincolo #1).

> ## >>> S337 ESITO (2026-06-04, voice-engineer): pjsip downgrade 2.16-dev → 2.15.1 ESEGUITO e VERIFICATO (`libVersion().full == 2.15.1`, build da sorgente iMac, SWIG 4.4.1, static x86_64 Big Sur, installato in `lib/pjsua2/`). **MA Sara CRASHA ANCORA identico sull'INVITE loopback** (SARA_DEAD, mai 200 OK, harness solo `100 Trying`→timeout). **2.15.1 HA LA STESSA op-queue asincrona di 2.16-dev** — log Sara mostra ancora `conference.c onCallMediaS "Add port N queued"` + `possibly re-registering existing thread`. **L'ipotesi "2.15.1 è sincrona" era SBAGLIATA.** <<<
> ## ROOT CAUSE REALE (rivista): STRUTTURALE, non version-specific. Sara fa port-add conference da thread `onCallMediaState`; group-lock unset su `_pjsua2_thread` in `libHandleEvents` → mismatch owner → abort. Il downgrade non tocca questo.
> ## NEXT S338 (decisione architetturale founder/main, NO 3° fix Python — REGOLA #1c): opzione (1) forzare port-add nel contesto del thread pjsua worker (`libRegisterThread`/eseguire add dentro l'event thread così l'owner del group-lock combacia); opzione (2) ESCALATION Asterisk ARI (N5 dossier) come layer SIP/media, Sara solo cervello — elimina la conference bridge pjsua2. Dettaglio completo: `.claude/agent-memory/voice-engineer/project_sip_loopback_crash_pjsip216.md` (sezione S337 UPDATE).
> ## Stato lib iMac: pjsua2 2.15.1 installato in `lib/pjsua2/`; backup 2.16-dev = `lib/pjsua2.backup-PRE-S337-20260604-125255/` (22MB, restore point). Nessun motivo di revertire (nessuna delle 2 versioni funziona per loopback). Sara pipeline DOWN dopo l'ultimo crash harness — riavviarla all'inizio S338.

> --- HANDOFF S337 ORIGINALE (parzialmente superato) ---
# FLUXION — S337 resume — Sara Layer 2 audio. **ROOT CAUSE TROVATA: pjsip 2.16-dev. NEXT = downgrade pjsip 2.15.1.**

> Scritto 2026-06-03 a chiusura S336. **FINDING DECISIVO**: l'INVITE SIP diretto P2P all'iMac FUNZIONA (gate sbloccato lato routing), ma la pipeline Sara **crasha** processando l'INVITE per un bug di **pjsip 2.16-dev** (op-queue / group-lock owner-thread sul commit della conference port). Il crash NON è chiudibile lato Python. **Unica via: downgrade pjsip → 2.15.1** (conference sincrona, niente op-queue). Gate Sara Layer 2 NON raggiunto = handoff strutturato, non verde.

> ## >>> PRIMA AZIONE S337: downgrade pjsip 2.16-dev → 2.15.1 sull'iMac, poi ri-run harness. <<<
> Delegare a voice-engineer (REGOLA #25, foreground per SSH/Bash). Runbook = "S244 path B1". Dopo il downgrade: ri-lanciare `voice-agent/scripts/sara_audio_harness.py` con INVITE diretto e validare il flusso audio E2E. Memory dettagliata dell'agent: `.claude/agent-memory/voice-engineer/project_sip_loopback_crash_pjsip216.md`.

## STATO — cosa è SOLIDO (non rifare)
- ✅ **INVITE diretto FUNZIONA** (chiude TODO[SIP-LIVE] ~36/~345). URI vincente: `sip:0972536918@127.0.0.1:5080` (harness su `127.0.0.1:5070`). Sara risponde `100 Trying` + `Answering call 0: code=200`, codec speex negoziato, bridge `sara_bridge` creato. La registrazione EHIWEB 403 è IRRILEVANTE per il test loopback (confermato).
- ✅ Harness `voice-agent/scripts/sara_audio_harness.py` (committato 196b491) = CORRETTO, non modificarlo. WAV TX gen OK (PCM16 8kHz mono, ricetta `say -o raw.aiff` + `afconvert -f WAVE -d LEI16@8000 -c 1`).
- ✅ Layer 1 testo VERDE (S333: 50 OK / 3 WARN / 0 FAIL su 12 verticali) — path HTTP `/api/voice/process`, NON tocca SIP, NON impattato dal bug.

## ROOT CAUSE (pjsip 2.16-dev) — diagnosi S336 completa
- Crash via `faulthandler`: `Fatal Python error: Aborted (SIGABRT)` nel thread `_pjsua2_thread` dentro `libHandleEvents` (`voip_pjsua2.py:806`), preceduto da pjsip C-log `conference.c onCallMediaS "Add port N queued"` + `os_core_unix.c "possibly re-registering existing thread"`. È l'assertion `grp_lock_unset_owner_thread` (lock.c): owner del group-lock settato dal thread di callback `onCallMediaState`, unset da `_pjsua2_thread`.
- pjsip attivo = **2.16-dev** (`libVersion` verificato). L'INVITE loopback dispatcha `onCallMediaState` su un media-thread dedicato → espone la race che le chiamate provider (S244) evitavano per timing.
- **Fix S243 esistente** (deferiva `startTransmit` nel drainer `drain_pending_bridges`) = INSUFFICIENTE: lasciava `createPort` dentro `onCallMediaState`.
- **Fix S335 tentato** (deferiva ANCHE la port creation `ensure_port`+`getAudioMedia` nel drainer): ha solo SPOSTATO il crash da `Add port 2 (sara_bridge)` → `Add port 1` (conference-port della call-leg, creata INTERNAMENTE da pjsip durante `answer()`, fuori dal controllo Python). **Conclusione: il bug op-queue 2.16-dev colpisce porte che non gestiamo → NON chiudibile lato Python.**

## S337 — PIANO (CTO, REGOLA #15)
1. **Downgrade pjsip 2.16-dev → 2.15.1** (iMac, runbook S244 path B1). NB: 2.15.1 ha conference API SINCRONA (`Conf add port N` immediato, niente op-queue) → niente owner-thread mismatch. Verificare che il path chiamate provider (S244) resti funzionante. Delegare a voice-engineer.
   - NON usare il backup `lib/pjsua2.backup-2.16dev-20260515` (è ancora 2.16-dev, stesso bug). Serve build/lib 2.15.1 reale.
2. **Ri-run harness** con INVITE diretto `sip:0972536918@127.0.0.1:5080`, WAV "Buongiorno, vorrei prenotare un appuntamento" → Sara NON crasha → 200 OK trasmesso → bridge attivo → cattura risposta RTP di Sara su WAV (durata >0) → trascrivi (whisper.cpp/Groq) → verifica Sara ha CAPITO+risposto pertinente. Chiude TODO[SIP-LIVE] ~273 (bridge wiring) e ~374 (cattura RTP).
3. **Estendere a golden-path per verticale via audio** (REGOLA #21: "soddisfa pienamente il cliente"). Scenari STT-sensitivi via audio; il resto già VERDE Layer 1 testo.

## STATO iMac (per ripartenza pulita)
- Branch iMac = `fix/license-interop-r01-s327` (preesistente da R-01, NON master). Tree pulito.
- **Fix S335 STASHATO** (recuperabile): `git stash list` → `stash@{0}` "s335-sip-loopback-fix-pjsip216-deferred-port". Backup pre-fix: `/tmp/voip_pjsua2.py.bak-s335-1780518361` (volatile, /tmp). **Probabilmente reso SUPERFLUO dal downgrade 2.15.1** (niente op-queue → niente deferral necessario). Recuperare solo se 2.15.1 mostrasse ancora una race.
- Pipeline Sara: UP+healthy (era PID 3410; il processo in memoria aveva il fix S335 caricato, il disco è ora a HEAD post-stash — il downgrade comporterà comunque restart, stato si normalizza).

## BLOCKED-ON (Luke/esterno, NON blocca gate Sara Layer 2)
- EHIWEB reset binding SIP (`reg_status:403` persistente): serve SOLO per chiamate clienti reali in prod, NON per il test CTO-guidato loopback. Ri-escalation operatore: reset garantito non ha funzionato; verificare reset propagato + IP whitelist (IP pubblico iMac `151.72.9.90`) + account/credito; se password rigenerata → aggiornare `voice-agent/.env` VOIP_SIP_PASS.
- Custom domain `fluxion-app.com`: NS su CF, no record A → attaccare a worker prod per go-live brandizzato.
- Rami client-side license tsc-only (offline grace/clock-rollback/banner): GUI iMac Keychain (REGOLA #12).
